---
version: 2.1

commands:
  ubuntu-install-pip3:
    description: "Install pip3 onto image"
    steps:
      - run:
          name: Get Python3 Version
          command: python3 --version
      - run:
          name: Update apt
          command: sudo apt update
      - run:
          name: Install pip3
          command: sudo apt install python3-pip
      - run:
          name: Get pip3 version
          command: pip3 --version

jobs:
  lint:
    docker:
      - image: cimg/base:stable-20.04
    steps:
      - checkout
      - ubuntu-install-pip3
      - run:
          name: Install all python linting tools for project
          command: make install-python-lint
      - run:
          name: Install hadolint for docker linting
          command: sudo make install-hadolint
      - run:
          name: Lint Python Unit Tests
          command: make lint-python
      - run:
          name: Lint Dockerfile for scrape-api
          command: make lint-docker
      - run:
          name: Lint AWS CloudFormation Templates
          command: make lint-aws-cf
  
  build-and-test:
    docker:
      - image: cimg/base:stable-20.04
    steps:
      - checkout
      - ubuntu-install-pip3
      - run:
          name: Install all Python Application Libraries
          command: make install-scrape-api
      - run:
          name: Install all Python Unit Test Libraries
          command: make install-unit-test
      - run:
          name: Run Python Application
          command: python3 src/scrape-api/app/app.py
      - run:
          name: Python Unit Tests
          command: make test-unit

workflows:
  blue-green-pipeline:
    jobs:
      - lint
      - build-and-test:
          requires:
            - lint
...