---
version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/base:stable-20.04
    steps:
      - checkout
      - run:
          name: Get Python3 Version
          command: python3 --version
      - run:
          name: Install all linting tools for project
          command: make install-lint
      - run:
          name: Lint Python Unit Tests
          command: make lint-python
      - run:
          name: Lint Dockerfile for scrape-api
          command: make lint-docker
      - run:
          name: Lint AWS CloudFormation Templates
          command: make lint-aws-cf
  
  build-and-test:
    docker:
      - image: cimg/base:stable-20.04
    steps:
      - checkout
      - run:
          name: Install all Python Application Libraries
          command: make install-scrape-api
      - run:
          name: Install all Python Unit Test Libraries
          command: make install-unit-test
      - run:
          name: Run Python Application
          command: python3 src/scrape-api/app.py
      - run:
          name: Python Unit Tests
          command: make test-unit

workflows:
  blue-green-pipeline:
    jobs:
      - lint
      - build-and-test:
          requires:
            - lint
...